name: sudoku_helper
description: "Classic Sudoku assistant with candidate management and logical hints."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  image: ^4.10.1
  tflite_flutter: ^0.12.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - path: assets/models/
      platforms: [android, ios, macos, linux, windows]
